[project]
name = "honours"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "aider-chat>=0.16.3",
    "dotenv>=0.9.9",
    "matplotlib>=3.9.4",
    "pandas>=2.3.1",
]
